### ISSUE TITLE
HW3关于glCreateShader的声明

### ISSUE THREAD

**Issue by qq33899** [sysucg2019/sysucg2019.github.io#10]
我用HW3模板运行程序，结果发现报错：error: use of undeclared identifier 'glCreateShader'; did you mean '__glewCreateShader'?

该怎么声明'glCreateShader'呢？

**Comment by sysucg2019** [comment]
glCreateShader在QOpenGLFunctions头文件中，你可能需要继承它以使用shader及vbo相关函数，如：
class MyGLWidget: public QOpenglWidget, protected QOpenGLFunctions {
…
};
这一点已经更新到模板中。

**Comment by qq33899** [comment]
谢谢解答
