### ISSUE TITLE
关于 glGetUniformLocation 的返回值

### ISSUE THREAD

**Issue by zengtianyu1215** [sysucg2019/sysucg2019.github.io#11]
在本次 Lab 3 实验中，我使用 glGetUniformLocation 函数对 shader 中的 uniform 类型的变量进行赋值，但是在较新版本的 OpenGL 中会出现返回值为 -1 （即没有找到）的情况。

我查阅了OpenGL官方文档，上面说 GLSL 编译器可能会对未使用的变量进行删去，而我运行课件上面正确的示例代码依然存在此问题。请问如何解决此问题呢？谢谢。

**Comment by sysucg2019** [comment]
非常抱歉，我尝试复现你所提到的情况，但是没有遇到此问题。  
仅凭描述难以分析出产生该问题的准确原因，因此这里提供一些可能的参考：  
[glGetUniformLocation returns -1 for existing uniform](https://community.khronos.org/t/glgetuniformlocation-returns-1-for-exisitng-unifo/60054),  
[glGetUniformLocation returns -1 for used variable](https://stackoverflow.com/questions/27735153/glgetuniformlocation-returns-1-for-used-variable-hell-with-optimization), 
[program not finding my uniforms](https://www.gamedev.net/forums/topic/605895-program-not-finding-my-uniforms/)

**Comment by zengtianyu1215** [comment]
我使用的是ubuntu 18.04，OpenGL 4.6，用了 glfw3、glad、glm 库，但是编译会产生冲突，而且无法使用初贴图之外的方式实现将一个点变成球，貌似是 Qt 自带的 OpenGL 和那几个库发生了冲突。请问 TA 能给一个 demo 吗？谢谢。

**Comment by sysucg2019** [comment]
你看下这一份Demo是否可以正常运行：[CG_Hw3demo](https://github.com/sysucg2019/sysucg2019.github.io/raw/master/CG_Hw3demo.zip)。  

另外，用点绘制球可以考虑通过在球的参数方程上取点实现，不需要借助除QT自有库之外的其他库。
