### ISSUE TITLE
glDrawArrays使用

### ISSUE THREAD

**Issue by qq33899** [sysucg2019/sysucg2019.github.io#13]
HW3中使用glDrawArrays来绘制球，点的位置是小球的面上的位置，这样可以吗（因为作业三中有要求，每个glVertex调用指明一个小球的球心位置 ，对此不是很明白。。。）

**Comment by sysucg2019** [comment]
"点的位置是小球面上的位置"是OK的。
"每个glVertex调用指明一个小球的球心位置"是指点的法向量指向小球球心。在OpenGL中，glVertex调用时会被赋予当前设置的法向量，法向量可以通过glNormal设置。
特别地，HW3要求使用shader实现这一过程。

**Comment by qq33899** [comment]
哦，谢谢助教

**Comment by qq33899** [comment]
感谢解答啦

**Comment by sysucg2019** [comment]
不客气。  
另外，[Assignment](https://sysucg2019.github.io/assignment)中更新了大作业的详细提交要求，望周知。
