### ISSUE TITLE
期末大作业要求的疑问

### ISSUE THREAD

**Issue by LinNan1** [sysucg2019/sysucg2019.github.io#14]
师兄你好！期末大作业要求里的，需要提交的报告文档中有分为小组和个人，意思是说，如果我们小组有3个人，就需要写4份报告，一份是小组的报告，内容是大作业的概述，还有3份报告，是小组成员各自所做的工作，即对大作业的贡献。请问是这样子的吗？

**Comment by sysucg2019** [comment]
大作业的详细提交要求已经更新到：[Assignment](https://sysucg2019.github.io/assignment)
