### ISSUE TITLE
这套 Jekyll 主题挺好看的，请问是助教自己写的吗？

### ISSUE THREAD

**Issue by szzhiyang** [sysucg2019/sysucg2019.github.io#2]
最近在学习 Jekyll，想交流一下。 😄

**Comment by sysucg2019** [comment]
是的，有兴趣的话可以仔细看一下[_includes](https://github.com/sysucg2019/sysucg2019.github.io/tree/master/_includes)和[_layouts](https://github.com/sysucg2019/sysucg2019.github.io/tree/master/_layouts)文件夹下的html和css文件，或者直接看整个工程[sysucg2019.github.io](https://github.com/sysucg2019/sysucg2019.github.io)。
界面做得比较简单，熟悉web的话应该很快就能理解。
有其他问题也可以具体提问。

**Comment by szzhiyang** [comment]
好的，感谢。 🙏
