### ISSUE TITLE
关于课件ppt的更新

### ISSUE THREAD

**Issue by qq33899** [sysucg2019/sysucg2019.github.io#5]
我想问一下，以后的上课用的ppt是否可以在上课前发出来呢？

**Comment by sysucg2019** [comment]
部分课件内容不会在上课前提早确定下来，可能会持续修改。  
目前只能说尽量满足同学们的要求，但不保证一定能在上课之前上传课件。

**Comment by qq33899** [comment]
哦哦哦，好的，感谢
