### ISSUE TITLE
关于project1实现的平移旋转

### ISSUE THREAD

**Issue by littlespray** [sysucg2019/sysucg2019.github.io#6]
请问是只需要实现平移旋转的功能就行(也就是只计算出平移旋转后的位置，而后重新描点连线)
还是需要完全重新实现glTranslatef()这些函数(也就是除了计算外，还要实现对OpenGL矩阵出入栈机制)？

**Comment by sysucg2019** [comment]
按照作业要求构造变换矩阵，然后使用矩阵乘法实现变换即可。
