### ISSUE TITLE
lab3: Use GL_POINTS to draw a sphere

### ISSUE THREAD

**Issue by littlespray** [sysucg2019/sysucg2019.github.io#9]
I spent a lot of time thinking about how to use GL_POINTS to draw a sphere but failed.

Should we just calculate the coordinates of numerous points on the surface of the sphere and draw them one by one? I would be very appreciated if you could give some tips.

**Comment by sysucg2019** [comment]
One possible approach is to sample points from the parametric equations of a sphere.
